// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/services.dart';

import 'core/env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: Env.value.apiKeyWeb,
    appId: Env.value.appIdWeb,
    messagingSenderId: Env.value.messagingSenderId,
    projectId: Env.value.projectId,
    authDomain: Env.value.authDomain,
    storageBucket: Env.value.storageBucket,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: Env.value.apiKeyAndroid,
    appId: appFlavor == 'development'
        ? Env.value.appIdAndroid
        : Env.value.appIdAndroid,
    messagingSenderId: Env.value.messagingSenderId,
    projectId: Env.value.projectId,
    storageBucket: Env.value.storageBucket,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.value.apiKeyIos,
    appId: Env.value.appIdIos,
    messagingSenderId: Env.value.messagingSenderId,
    projectId: Env.value.projectId,
    storageBucket: Env.value.storageBucket,
    iosBundleId: Env.value.iosBundleId,
  );
}
